
/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AccessibilityUtilities.framework/AccessibilityUtilities
 */

@interface AXSettings : NSObject

@property bool reduceMotionEnabled;

+ (id)sharedInstance;

- (void)setReduceMotionEnabled:(bool)arg1;
- (bool)reduceMotionEnabled;

@end
